DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS(ID LONG AUTO_INCREMENT PRIMARY KEY,MATRICULA INT NOT NULL,  NOMBRE VARCHAR(25) NOT NULL, APELLIDO VARCHAR(25) NOT NULL);

INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES ('51095995', 'Chiara', 'Pozzi'), ('62481200', 'Carlos', 'Colmenares'), ('65418268', 'Juancito', 'Perez'), ('54825781', 'Ana','Fulana');