DROP TABLE IF EXISTS DOMICILIOS; CREATE TABLE DOMICILIOS (ID LONG AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(50) NOT NULL, NUMERO INT NOT NULL, LOCALIDAD VARCHAR(50) NOT NULL, PROVINCIA VARCHAR(50) NOT NULL);

DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS(ID LONG AUTO_INCREMENT PRIMARY KEY,MATRICULA INT NOT NULL,  NOMBRE VARCHAR(25) NOT NULL, APELLIDO VARCHAR(25) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (ID LONG AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, DNI INT NOT NULL, FECHA DATE NOT NULL, DOMICILIO_ID LONG);

DROP TABLE IF EXISTS TURNOS;
CREATE TABLE TURNOS (ID LONG AUTO_INCREMENT PRIMARY KEY, PACIENTE_ID  LONG NOT NULL, ODONTOLOGO_ID LONG NOT NULL, FECHA DATE NOT NULL);



INSERT INTO DOMICILIOS(CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Av Siempre Viva', 742, 'Springfield', 'Massachusetts'), ('Calle Wallaby', 42, 'Sydney', 'Nueva Gales del Sur');

INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES ('51095995', 'Chiara', 'Pozzi'), ('62481200', 'Carlos', 'Colmenares'), ('65418268', 'Juancito', 'Perez'), ('54825781', 'Ana','Fulana');

INSERT INTO PACIENTES (NOMBRE, APELLIDO, DNI, FECHA) VALUES ('Chiara', 'PozzitoDeAgua', 51095995, '2023-05-24'), ('Carlos', 'ColmenaDeAbejas', '62481200','2023-05-24');

INSERT INTO TURNOS (PACIENTE_ID, ODONTOLOGO_ID, FECHA) VALUES ('1', '2', '2023-05-24'), ('2', '1','2023-05-24');

